(require "helix/components.scm")
(require "helix/themes.scm")

(provide ashen-theme)

;; Ashen Palette
(define cursorline "#191919")
(define text "#b4b4b4")
(define red_flame "#C53030")
(define red_glowing "#DF6464")
(define red_ember "#B14242")
(define orange_glow "#D87C4A")
(define orange_blaze "#C4693D")
(define orange_muted "#6D3B22")
(define orange_smolder "#E49A44")
(define orange_golden "#E5A72A")
(define golden_muted "#6D4D0D")
(define brown "#89492a")
(define brown_dark "#322119")
(define blue "#4A8B8B")
(define background "#121212")
(define g_1 "#e5e5e5")
(define g_2 "#d5d5d5")
(define g_3 "#b4b4b4")
(define g_4 "#a7a7a7")
(define g_5 "#949494")
(define g_6 "#737373")
(define g_7 "#535353")
(define g_8 "#323232")
(define g_9 "#212121")
(define g_10 "#1d1d1d")
(define g_11 "#191919")
(define g_12 "#151515")

;; Base theme hash
(define ashen-hash
  (hash
   "ui.background" (hash 'fg text 'bg background)
   "ui.linenr" (hash 'fg g_8)
   "ui.linenr.selected" (hash 'fg g_6)))

(define ashen-theme (hashmap->theme "ashen" ashen-hash))

;; Syntax Highlighting
(theme-set-style! ashen-theme 'attribute (~> (style) (style-fg (string->color g_4))))
(theme-set-style! ashen-theme 'type (~> (style) (style-fg (string->color blue))))
(theme-set-style! ashen-theme 'type.builtin (~> (style) (style-fg (string->color blue))))
(theme-set-style! ashen-theme 'type.parameter (~> (style) (style-fg (string->color orange_glow))))
(theme-set-style! ashen-theme 'type.enum.variant (~> (style) (style-fg (string->color orange_blaze))))
(theme-set-style! ashen-theme 'constructor (~> (style) (style-fg (string->color g_1))))
(theme-set-style! ashen-theme 'constant (~> (style) (style-fg (string->color orange_blaze))))
(theme-set-style! ashen-theme 'constant.builtin (~> (style) (style-fg (string->color blue))))
(theme-set-style! ashen-theme 'constant.character (~> (style) (style-fg (string->color red_glowing)) style-with-bold))
(theme-set-style! ashen-theme 'constant.character.escape (~> (style) (style-fg (string->color g_2))))
(theme-set-style! ashen-theme 'constant.numeric (~> (style) (style-fg (string->color blue))))
(theme-set-style! ashen-theme 'string (~> (style) (style-fg (string->color orange_smolder))))
(theme-set-style! ashen-theme 'string.regexp (~> (style) (style-fg (string->color orange_glow))))
(theme-set-style! ashen-theme 'string.special (~> (style) (style-fg (string->color g_2))))
(theme-set-style! ashen-theme 'string.special.url (~> (style) (style-fg (string->color red_glowing)) style-with-bold))
(theme-set-style! ashen-theme 'string.special.path (~> (style) (style-fg (string->color red_glowing)) style-with-bold))
(theme-set-style! ashen-theme 'string.special.symbol (~> (style) (style-fg (string->color orange_smolder))))
(theme-set-style! ashen-theme 'comment (~> (style) (style-fg (string->color g_6)) style-with-italics))
(theme-set-style! ashen-theme 'comment.block.documentation (~> (style) (style-fg (string->color g_5)) style-with-italics))
(theme-set-style! ashen-theme 'comment.line.documentation (~> (style) (style-fg (string->color g_5)) style-with-italics))
(theme-set-style! ashen-theme 'variable (~> (style) (style-fg (string->color text))))
(theme-set-style! ashen-theme 'variable.parameter (~> (style) (style-fg (string->color g_2)) style-with-italics))
(theme-set-style! ashen-theme 'variable.builtin (~> (style) (style-fg (string->color blue))))
(theme-set-style! ashen-theme 'variable.other.member (~> (style) (style-fg (string->color g_2))))
(theme-set-style! ashen-theme 'label (~> (style) (style-fg (string->color red_ember))))
(theme-set-style! ashen-theme 'punctuation (~> (style) (style-fg (string->color g_2))))
(theme-set-style! ashen-theme 'punctuation.special (~> (style) (style-fg (string->color orange_golden))))
(theme-set-style! ashen-theme 'punctuation.bracket (~> (style) (style-fg (string->color g_6))))
(theme-set-style! ashen-theme 'punctuation.delimiter (~> (style) (style-fg (string->color orange_smolder))))
(theme-set-style! ashen-theme 'keyword (~> (style) (style-fg (string->color orange_blaze)) style-with-bold))
(theme-set-style! ashen-theme 'keyword.operator (~> (style) (style-fg (string->color orange_blaze))))
(theme-set-style! ashen-theme 'keyword.directive (~> (style) (style-fg (string->color red_ember)) style-with-italics))
(theme-set-style! ashen-theme 'keyword.storage.modifier (~> (style) (style-fg (string->color red_ember)) style-with-italics))
(theme-set-style! ashen-theme 'operator (~> (style) (style-fg (string->color orange_glow))))
(theme-set-style! ashen-theme 'function (~> (style) (style-fg (string->color blue)) style-with-bold))
(theme-set-style! ashen-theme 'function.builtin (~> (style) (style-fg (string->color blue)) style-with-bold style-with-italics))
(theme-set-style! ashen-theme 'function.macro (~> (style) (style-fg (string->color red_ember))))
(theme-set-style! ashen-theme 'tag (~> (style) (style-fg (string->color orange_glow)) style-with-italics))
(theme-set-style! ashen-theme 'namespace (~> (style) (style-fg (string->color orange_glow)) style-with-bold))
(theme-set-style! ashen-theme 'special (~> (style) (style-fg (string->color orange_smolder))))

;; Markup
(theme-set-style! ashen-theme 'markup.heading (~> (style) (style-fg (string->color red_glowing)) style-with-bold))
(theme-set-style! ashen-theme 'markup.list (~> (style) (style-fg (string->color orange_glow))))
(theme-set-style! ashen-theme 'markup.bold (~> (style) style-with-bold))
(theme-set-style! ashen-theme 'markup.italic (~> (style) style-with-italics))
(theme-set-style! ashen-theme 'markup.link.url (~> (style) (style-fg (string->color red_glowing)) style-with-italics (style-underline-style Underline/Line)))
(theme-set-style! ashen-theme 'markup.link.text (~> (style) (style-fg (string->color red_ember))))
(theme-set-style! ashen-theme 'markup.raw (~> (style) (style-fg (string->color g_2)) (style-bg (string->color g_10))))
(theme-set-style! ashen-theme 'markup.quote (~> (style) style-with-italics))

;; Diff
(theme-set-style! ashen-theme 'diff.plus (~> (style) (style-fg (string->color g_6))))
(theme-set-style! ashen-theme 'diff.minus (~> (style) (style-fg (string->color red_ember))))
(theme-set-style! ashen-theme 'diff.delta (~> (style) (style-fg (string->color brown))))

;; User Interface
(theme-set-style! ashen-theme 'ui.statusline (~> (style) (style-fg (string->color g_3)) (style-bg (string->color g_9))))
(theme-set-style! ashen-theme 'ui.statusline.inactive (~> (style) (style-fg (string->color g_5)) (style-bg (string->color g_10))))
(theme-set-style! ashen-theme 'ui.statusline.normal (~> (style) (style-fg (string->color background)) (style-bg (string->color orange_blaze)) style-with-bold))
(theme-set-style! ashen-theme 'ui.statusline.insert (~> (style) (style-fg (string->color g_1)) (style-bg (string->color g_7)) style-with-bold))
(theme-set-style! ashen-theme 'ui.statusline.select (~> (style) (style-fg (string->color background)) (style-bg (string->color orange_golden)) style-with-bold))
(theme-set-style! ashen-theme 'ui.popup (~> (style) (style-fg (string->color text)) (style-bg (string->color g_10))))
(theme-set-style! ashen-theme 'ui.window (~> (style) (style-fg (string->color g_7))))
(theme-set-style! ashen-theme 'ui.help (~> (style) (style-fg (string->color text)) (style-bg (string->color g_10)) style-with-bold))
(theme-set-style! ashen-theme 'ui.bufferline (~> (style) (style-fg (string->color text)) (style-bg (string->color background))))
(theme-set-style! ashen-theme 'ui.bufferline.background (~> (style) (style-bg (string->color background))))
(theme-set-style! ashen-theme 'ui.bufferline.active (~> (style) (style-fg (string->color g_2)) (style-bg (string->color g_10)) style-with-bold (style-underline-style Underline/Line)))
(theme-set-style! ashen-theme 'ui.text (~> (style) (style-fg (string->color text))))
(theme-set-style! ashen-theme 'ui.text.inactive (~> (style) (style-fg (string->color g_7))))
(theme-set-style! ashen-theme 'ui.text.directory (~> (style) (style-fg (string->color red_ember))))
(theme-set-style! ashen-theme 'ui.text.focus (~> (style) (style-fg (string->color g_2)) (style-bg (string->color g_10)) style-with-bold (style-underline-style Underline/Line)))
(theme-set-style! ashen-theme 'ui.virtual (~> (style) (style-fg (string->color g_5))))
(theme-set-style! ashen-theme 'ui.virtual.ruler (~> (style) (style-bg (string->color cursorline))))
(theme-set-style! ashen-theme 'ui.virtual.whitespace (~> (style) (style-fg (string->color g_7))))
(theme-set-style! ashen-theme 'ui.virtual.indent-guide (~> (style) (style-fg (string->color g_7))))
(theme-set-style! ashen-theme 'ui.virtual.wrap (~> (style) (style-fg (string->color g_7))))
(theme-set-style! ashen-theme 'ui.virtual.inlay-hint (~> (style) (style-fg (string->color g_6)) style-with-italics))
(theme-set-style! ashen-theme 'ui.virtual.jump-label (~> (style) (style-fg (string->color background)) (style-bg (string->color orange_blaze)) style-with-bold))
(theme-set-style! ashen-theme 'ui.selection (~> (style) (style-bg (string->color brown_dark))))
(theme-set-style! ashen-theme 'ui.cursorline (~> (style) (style-bg (string->color g_12))))
(theme-set-style! ashen-theme 'ui.cursorline.primary (~> (style) (style-bg (string->color cursorline))))
(theme-set-style! ashen-theme 'ui.menu (~> (style) (style-fg (string->color g_2)) (style-bg (string->color g_10))))
(theme-set-style! ashen-theme 'ui.menu.selected (~> (style) (style-fg (string->color background)) (style-bg (string->color orange_blaze)) style-with-bold))
(theme-set-style! ashen-theme 'ui.info (~> (style) (style-fg (string->color orange_blaze)) (style-bg (string->color g_10))))

;; Cursors
(theme-set-style! ashen-theme 'ui.cursor.normal (~> (style) (style-fg (string->color background)) (style-bg (string->color orange_muted))))
(theme-set-style! ashen-theme 'ui.cursor.insert (~> (style) (style-fg (string->color background)) (style-bg (string->color g_7))))
(theme-set-style! ashen-theme 'ui.cursor.select (~> (style) (style-fg (string->color background)) (style-bg (string->color golden_muted))))
(theme-set-style! ashen-theme 'ui.cursor.primary.normal (~> (style) (style-fg (string->color background)) (style-bg (string->color orange_blaze)) style-with-bold))
(theme-set-style! ashen-theme 'ui.cursor.primary.insert (~> (style) (style-fg (string->color background)) (style-bg (string->color g_3)) style-with-bold))
(theme-set-style! ashen-theme 'ui.cursor.primary.select (~> (style) (style-fg (string->color background)) (style-bg (string->color orange_golden)) style-with-bold))
(theme-set-style! ashen-theme 'ui.cursor.match (~> (style) (style-fg (string->color orange_smolder)) (style-underline-style Underline/Line)))

;; Highlight
(theme-set-style! ashen-theme 'ui.highlight (~> (style) (style-fg (string->color orange_blaze)) (style-bg (string->color cursorline)) style-with-bold (style-underline-style Underline/Line)))

;; Diagnostics
(theme-set-style! ashen-theme 'diagnostic.error (~> (style) (style-underline-style Underline/Curl) (style-underline-color (string->color red_flame))))
(theme-set-style! ashen-theme 'diagnostic.warning (~> (style) (style-underline-style Underline/Curl) (style-underline-color (string->color orange_golden))))
(theme-set-style! ashen-theme 'diagnostic.info (~> (style) (style-underline-style Underline/Dotted) (style-underline-color (string->color g_4))))
(theme-set-style! ashen-theme 'diagnostic.hint (~> (style) (style-underline-style Underline/Dotted) (style-underline-color (string->color g_5))))
(theme-set-style! ashen-theme 'diagnostic.unnecessary (~> (style) style-with-dim))

;; Error/Warning/Info/Hint
(theme-set-style! ashen-theme 'error (~> (style) (style-fg (string->color red_flame)) (style-bg (string->color g_10))))
(theme-set-style! ashen-theme 'warning (~> (style) (style-fg (string->color orange_golden)) (style-bg (string->color g_10))))
(theme-set-style! ashen-theme 'info (~> (style) (style-fg (string->color g_2)) (style-bg (string->color g_10))))
(theme-set-style! ashen-theme 'hint (~> (style) (style-fg (string->color g_4)) (style-bg (string->color g_10))))

(register-theme ashen-theme)
