[mgr]
sort_by = "natural"
linemode = "size"
show_symlink = true
show_hidden = true

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"